insert into Restaurants (rest_id, name, order_threshold) values (1, 'Littel-Schowalter', '$11.47');
insert into Restaurants (rest_id, name, order_threshold) values (2, 'Simonis and Sons', '$12.24');
insert into Restaurants (rest_id, name, order_threshold) values (3, 'Vandervort, Rice and Lehner', '$12.62');
insert into Restaurants (rest_id, name, order_threshold) values (4, 'Bergnaum LLC', '$14.06');
insert into Restaurants (rest_id, name, order_threshold) values (5, 'Abbott-Harris', '$11.18');
insert into Restaurants (rest_id, name, order_threshold) values (6, 'Streich-Predovic', '$11.94');
insert into Restaurants (rest_id, name, order_threshold) values (7, 'Streich, Brekke and Bednar', '$11.18');
insert into Restaurants (rest_id, name, order_threshold) values (8, 'Blick, Boyer and Schroeder', '$11.84');
insert into Restaurants (rest_id, name, order_threshold) values (9, 'Kirlin-Jacobson', '$10.36');
insert into Restaurants (rest_id, name, order_threshold) values (10, 'Ziemann-Halvorson', '$10.20');
